version: '3.8'

services: 
  web:
    image: nginx:alpine
    restart: always
    ports:
       - "80:80"
    volumes:
       - ./docker/nginx/:/etc/nginx/conf.d/
       - ./:/var/www
    networks:
       - exemple-network   

  php:
    image: php:8.0-fpm
    volumes:
       - ./:/var/www
    networks:
       - exemple-network  

networks:
  exemple-network:
    driver: bridge